name: Deploy to GitHub Pages

on:
  push:
    branches:
      - score-calculator-app  # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Shadow CLJS
        run: npm install

      - name: Build the project
        run: shadow-cljs release app  # Replace 'app' with your build target if different

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/js  # Adjust this path if your output directory is different
